#!/bin/bash

#SBATCH -N 1
#SBATCH -t 00:10:00
#SBATCH --sockets-per-node=2
#SBATCH --cores-per-socket=10
#SBATCH --threads-per-core=1
#SBATCH -p testing 
#SBATCH --exclusive

export OMP_NUM_THREADS=1
export OMP_AFFINITY=compact
./PeakFlops.out

export OMP_NUM_THREADS=2
export OMP_AFFINITY=compact
./PeakFlops.out

export OMP_NUM_THREADS=5
export OMP_AFFINITY=compact
./PeakFlops.out

export OMP_NUM_THREADS=10
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=20
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=40
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=80
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=160
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=320
export OMP_AFFINITY=balanced
./PeakFlops.out

export OMP_NUM_THREADS=640
export OMP_AFFINITY=balanced
./PeakFlops.out
